pub const SYMBOLS_PATTERNS: [(&str, &str); 28] = [
    ("!", "not"),
    ("%", "modulus"),
    ("&", "bitwise_and"),
    ("*", "multiply"),
    ("+", "addition"),
    ("-", "subtract"),
    ("/", "divide"),
    ("<", "less_than"),
    (">", "greater_than"),
    ("^", "xor"),
    ("|", "bitwise_or"),
    ("\"", "quote_double"),
    ("#", "pound"),
    ("$", "dollar"),
    ("'", "quote_single"),
    ("(", "paren_left"),
    (")", "parent_right"),
    (",", "comma"),
    (".", "dot"),
    (":", "colon"),
    (";", "semi"),
    ("=", "eq"),
    ("?", "question"),
    ("@", "at"),
    ("[", "bracket_left"),
    ("]", "bracket_right"),
    ("{", "brace_left"),
    ("}", "brace_right"),
];

pub const COMMON_PROGRAMMING_SYMBOL_PATTERNS: [(&str, &str); 24] = [
    ("!=", "_not_equal"),
    ("&&", "_and"),
    ("<<", "left_shift"),
    ("<=", "less_than_equal"),
    ("==", "equal"),
    (">=", "greater_than_equal"),
    (">>", "right_shift"),
    ("||", "or"),
    ("%=", "assign_modulus"),
    ("&=", "assign_bitwise_and"),
    ("*=", "assign_multiply"),
    ("+=", "assign_addition"),
    ("-=", "assign_subtract"),
    ("/=", "assign_divide"),
    ("<<=", "assign_left_shift"),
    (">>=", "assign_right_shift"),
    ("^=", "assign_xor"),
    ("|=", "assign_or"),
    ("->", "r_arrow"),
    ("..", "dot_dot"),
    ("...", "dot_dot_dot"),
    ("..=", "dot_dot_eq"),
    ("::", "path_sep"),
    ("=>", "fat_arrow"),
];
